class ConstantPool {
  static Map<String, String> fileExtensionIconMap = {
    "mp3": "assets/icons/icon_audio.png",
    "wav": "assets/icons/icon_audio.png",
    "doc": "assets/icons/icon_doc.png",
    "docm": "assets/icons/icon_docm.png",
    "docx": "assets/icons/icon_docx.png",
    "dot": "assets/icons/icon_dot.png",
    "dotm": "assets/icons/icon_dotm.png",
    "dotx": "assets/icons/icon_dotx.png",
    "page": "assets/icons/icon_page.png",
    "pages": "assets/icons/icon_pages.png",
    "pdf": "assets/icons/icon_pdf.png",
    "pot": "assets/icons/icon_pot.png",
    "potx": "assets/icons/icon_potx.png",
    "ppt": "assets/icons/icon_ppt.png",
    "pptm": "assets/icons/icon_pptm.png",
    "pptx": "assets/icons/icon_pptx.png",
    "txt": "assets/icons/icon_txt.png",
    "xls": "assets/icons/icon_xls.png",
    "xlsx": "assets/icons/icon_xlsx.png",
    "xlt": "assets/icons/icon_xlt.png",
    "xltx": "assets/icons/icon_xltx.png",
    "zip": "assets/icons/icon_zip.png",
    "other": "assets/icons/icon_other.png",
    "key": "assets/icons/icon_key.png",
    "apk": "assets/icons/icon_apk.png",
    "jpg": "assets/icons/ic_image.png",
    "png": "assets/icons/ic_image.png",
    "jpeg": "assets/icons/ic_image.png",
    "webp": "assets/icons/ic_image.png",
    "gif": "assets/icons/ic_image.png",
    "bmp": "assets/icons/ic_image.png",
    "jfif": "assets/icons/ic_image.png",
    "pjpeg": "assets/icons/ic_image.png",
    "pjp": "assets/icons/ic_image.png",
    "svg": "assets/icons/ic_image.png",
    "ico": "assets/icons/ic_image.png",
    "tif": "assets/icons/ic_image.png",
    "tiff": "assets/icons/ic_image.png",
    "raw": "assets/icons/ic_image.png"
  };
}
